"""Adding elo changes

Revision ID: 38ade80163af
Revises:
Create Date: 2025-09-04 20:28:46.176918

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38ade80163af"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playerelohistory", sa.Column("is_reverted", sa.Boolean(), nullable=False, server_default="0"))
    op.add_column("playerelohistory", sa.Column("change", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playerelohistory", "change")
    op.drop_column("playerelohistory", "is_reverted")
    # ### end Alembic commands ###
