"""Add champions

Revision ID: c0ee891c9a51
Revises: cf6520b46e00
Create Date: 2025-09-06 22:17:02.685088

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0ee891c9a51"
down_revision: Union[str, Sequence[str], None] = "cf6520b46e00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playermatchchampion",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("champion_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "match_id"),
    )
    op.create_index(op.f("ix_playermatchchampion_champion_id"), "playermatchchampion", ["champion_id"], unique=False)
    op.create_index(op.f("ix_playermatchchampion_match_id"), "playermatchchampion", ["match_id"], unique=False)
    op.create_index(op.f("ix_playermatchchampion_player_id"), "playermatchchampion", ["player_id"], unique=False)
    op.add_column("match", sa.Column("champions_registered", sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "champions_registered")
    op.drop_index(op.f("ix_playermatchchampion_player_id"), table_name="playermatchchampion")
    op.drop_index(op.f("ix_playermatchchampion_match_id"), table_name="playermatchchampion")
    op.drop_index(op.f("ix_playermatchchampion_champion_id"), table_name="playermatchchampion")
    op.drop_table("playermatchchampion")
    # ### end Alembic commands ###
