"""Adding season final elo table

Revision ID: c7fd90001879
Revises: c948de022dea
Create Date: 2025-09-30 13:07:17.074534

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7fd90001879"
down_revision: Union[str, Sequence[str], None] = "c948de022dea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playerseasonfinalelo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playerseasonfinalelo_player_id"), "playerseasonfinalelo", ["player_id"], unique=False)
    op.create_index(op.f("ix_playerseasonfinalelo_season_id"), "playerseasonfinalelo", ["season_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_playerseasonfinalelo_season_id"), table_name="playerseasonfinalelo")
    op.drop_index(op.f("ix_playerseasonfinalelo_player_id"), table_name="playerseasonfinalelo")
    op.drop_table("playerseasonfinalelo")
    # ### end Alembic commands ###
