"""Changing team rating type

Revision ID: c948de022dea
Revises: 8861ac6466bf
Create Date: 2025-09-23 21:17:10.221182

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c948de022dea"
down_revision: Union[str, Sequence[str], None] = "8861ac6466bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("team", "team_rating", existing_type=sa.INTEGER(), type_=sa.Float(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("team", "team_rating", existing_type=sa.Float(), type_=sa.INTEGER(), existing_nullable=False)
    # ### end Alembic commands ###
