"""Add puuid

Revision ID: cf6520b46e00
Revises: 38ade80163af
Create Date: 2025-09-06 20:55:51.001024

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf6520b46e00"
down_revision: Union[str, Sequence[str], None] = "38ade80163af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("puuid", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f("ix_player_puuid"), "player", ["puuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_puuid"), table_name="player")
    op.drop_column("player", "puuid")
    # ### end Alembic commands ###
